### ISSUE TITLE
Docstring is inaccurate -- YOUR_DISEASE_NAME should be YOUR_DISEASE_NAME_observer

### ISSUE THREAD

**Issue by aflaxman** [ihmeuw/vivarium_public_health#130]
Docstring is inaccurate -- YOUR_DISEASE_NAME should be YOUR_DISEASE_NAME_observer

https://github.com/ihmeuw/vivarium_public_health/blob/f749db73c0e8b5f88e21e45f3161bac7f10ea9f9/src/vivarium_public_health/metrics/disease.py#L19

**Comment by halfhorst** [comment]
We fixed this a bit ago, left this open too long
